//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultimediaSysServer.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class jjj_ProgramSendSerialList
    {
        public int ProgramSendSerialID { get; set; }
        public int TerminalEquipmentID { get; set; }
        public int ProgramInfoID { get; set; }
        public Nullable<int> SendStatus { get; set; }
        public Nullable<System.DateTime> EfficaciousDateStart { get; set; }
        public Nullable<System.DateTime> EfficaciousDateEnd { get; set; }
        public Nullable<System.TimeSpan> EfficaciousTimeStart { get; set; }
        public Nullable<System.TimeSpan> EfficaciousTimeEnd { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> ReceiveBackTime { get; set; }
        public Nullable<System.DateTime> DownloadOverTime { get; set; }
    
        public virtual jjj_ProgramInfoList jjj_ProgramInfoList { get; set; }
        public virtual jjj_TerminalEquipmentList jjj_TerminalEquipmentList { get; set; }
    }
}
