//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultimediaSysServer.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class jjj_ProgramInfoList
    {
        public jjj_ProgramInfoList()
        {
            this.jjj_ProgramInfoListItem = new HashSet<jjj_ProgramInfoListItem>();
            this.jjj_ProgramSendSerialList = new HashSet<jjj_ProgramSendSerialList>();
        }
    
        public int ProgramInfoID { get; set; }
        public string ProgramTitle { get; set; }
        public Nullable<int> ProgramWidth { get; set; }
        public Nullable<int> ProgramHeight { get; set; }
        public Nullable<int> ProgramStatus { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public string ProgramClientId { get; set; }
        public string Second_Program_ServerBack { get; set; }
        public string ContainerClientId { get; set; }
        public string Second_Container_ServerBack { get; set; }
        public string ContainerLayout { get; set; }
        public string ContainerName { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
    
        public virtual ICollection<jjj_ProgramInfoListItem> jjj_ProgramInfoListItem { get; set; }
        public virtual ICollection<jjj_ProgramSendSerialList> jjj_ProgramSendSerialList { get; set; }
    }
}
