//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultimediaSysServer.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class jjj_user_OperatePower
    {
        public int id { get; set; }
        public Nullable<int> uid { get; set; }
        public Nullable<int> OperatePowerId { get; set; }
    
        public virtual jjj_BackgroundWeb_OperatePower jjj_BackgroundWeb_OperatePower { get; set; }
        public virtual jjj_users jjj_users { get; set; }
    }
}
