//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultimediaSysServer.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class jjj_adminsessions
    {
        public int adminsessionsId { get; set; }
        public Nullable<int> uid { get; set; }
        public string ip { get; set; }
        public Nullable<System.DateTime> dateline { get; set; }
        public Nullable<int> errorCount { get; set; }
        public Nullable<System.DateTime> allowDate { get; set; }
    
        public virtual jjj_users jjj_users { get; set; }
    }
}
