//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultimediaSysServer.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class jjj_users
    {
        public jjj_users()
        {
            this.jjj_adminsessions = new HashSet<jjj_adminsessions>();
            this.jjj_MaterialManagement = new HashSet<jjj_MaterialManagement>();
            this.jjj_MaterialManagementDetail = new HashSet<jjj_MaterialManagementDetail>();
            this.jjj_TerminalEquipmentList = new HashSet<jjj_TerminalEquipmentList>();
            this.jjj_user_OperatePower = new HashSet<jjj_user_OperatePower>();
        }
    
        public int uid { get; set; }
        public string username { get; set; }
        public string actualname { get; set; }
        public string password { get; set; }
        public string payPassword { get; set; }
        public Nullable<int> gender { get; set; }
        public string regip { get; set; }
        public Nullable<System.DateTime> joindate { get; set; }
        public string lastip { get; set; }
        public Nullable<System.DateTime> lastvisit { get; set; }
        public Nullable<decimal> credits { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> bday { get; set; }
        public Nullable<int> showemail { get; set; }
        public Nullable<int> invisible { get; set; }
        public Nullable<int> newpm { get; set; }
        public Nullable<int> newpmcount { get; set; }
        public Nullable<int> onlinestate { get; set; }
        public Nullable<int> groupid { get; set; }
        public string avatarimageURL { get; set; }
        public string qq { get; set; }
        public string site { get; set; }
        public string address { get; set; }
        public string postCode { get; set; }
        public string phone { get; set; }
        public string HideCode { get; set; }
        public Nullable<System.DateTime> getPwdLastTime { get; set; }
        public string medals { get; set; }
        public string openId { get; set; }
        public string accessToken { get; set; }
        public string identityCard { get; set; }
        public string identityimageURL { get; set; }
        public Nullable<decimal> PassTicket { get; set; }
        public Nullable<decimal> freezePassTicket { get; set; }
        public Nullable<decimal> shopPassTicket { get; set; }
        public string addressProvinceCode { get; set; }
        public string addressCityCode { get; set; }
        public string addressAreaCode { get; set; }
        public Nullable<int> consigneeAddressId { get; set; }
        public string HengYuCode { get; set; }
        public string commendHengYuCode { get; set; }
        public Nullable<int> isOldUser { get; set; }
        public Nullable<int> isEnable { get; set; }
        public Nullable<System.DateTime> acceptTime { get; set; }
        public Nullable<System.DateTime> activeTime { get; set; }
        public string agentHengYuCode { get; set; }
        public Nullable<int> businessNum { get; set; }
        public Nullable<int> businessTotalNum { get; set; }
        public string regValidatecode { get; set; }
        public Nullable<System.DateTime> ValidatecodeLastTime { get; set; }
        public string renwuOldSys { get; set; }
        public string phoneMSISDN { get; set; }
        public string phoneIMEI { get; set; }
        public string phoneModel { get; set; }
        public string phoneIMSI { get; set; }
        public Nullable<int> BossUid { get; set; }
        public Nullable<int> departmentId { get; set; }
        public string ZhiWu { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> baiduPush_responseParamID { get; set; }
        public string userNameRemark { get; set; }
        public string Signature { get; set; }
        public string tempPasswrod { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string LoginInfo { get; set; }
        public string Power { get; set; }
        public string Vcard { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public string OurMsgGroupID { get; set; }
        public Nullable<int> CurrentSecurityStatus { get; set; }
        public string WeiXin_UserName { get; set; }
        public string WeiXin_UserOpenID { get; set; }
        public string remark { get; set; }
        public string ucpaas_clientNum { get; set; }
        public string ucpaas_clientpwd { get; set; }
        public string TwoDimensionalCodeImg { get; set; }
        public string agentAdminHengYuCode { get; set; }
        public Nullable<int> WaitActivatedCredits { get; set; }
        public Nullable<int> ReserveCredits { get; set; }
        public string TempEmail { get; set; }
        public Nullable<System.DateTime> ValidateEmailDatetime { get; set; }
        public string ValidateEmailGuid { get; set; }
        public Nullable<bool> ValidateEmailStatus { get; set; }
        public Nullable<System.DateTime> AlterEmailDatetime { get; set; }
        public string AlterEmailGuid { get; set; }
        public Nullable<int> IsVipPrivilege { get; set; }
        public Nullable<bool> ValidatePhoneStatus { get; set; }
        public Nullable<decimal> JuHongBao { get; set; }
    
        public virtual ICollection<jjj_adminsessions> jjj_adminsessions { get; set; }
        public virtual ICollection<jjj_MaterialManagement> jjj_MaterialManagement { get; set; }
        public virtual ICollection<jjj_MaterialManagementDetail> jjj_MaterialManagementDetail { get; set; }
        public virtual ICollection<jjj_TerminalEquipmentList> jjj_TerminalEquipmentList { get; set; }
        public virtual ICollection<jjj_user_OperatePower> jjj_user_OperatePower { get; set; }
        public virtual jjj_usergroups jjj_usergroups { get; set; }
    }
}
