//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultimediaSysServer.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class jjj_TerminalSwitchScreenTime
    {
        public int TerminalSwitchScreenTimeID { get; set; }
        public int TerminalEquipmentID { get; set; }
        public Nullable<System.TimeSpan> TurnOnTime { get; set; }
        public Nullable<System.TimeSpan> TurnOffTime { get; set; }
        public Nullable<bool> IsMonday { get; set; }
        public Nullable<bool> IsTuesday { get; set; }
        public Nullable<bool> IsWednesday { get; set; }
        public Nullable<bool> IsThursday { get; set; }
        public Nullable<bool> IsFriday { get; set; }
        public Nullable<bool> IsSaturday { get; set; }
        public Nullable<bool> IsSunday { get; set; }
        public Nullable<bool> IsEnable { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> IsSend { get; set; }
    }
}
