//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultimediaSysServer.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class jjj_ProgramInfoListItem
    {
        public jjj_ProgramInfoListItem()
        {
            this.jjj_ProgramInfoItem_DocumentDetail = new HashSet<jjj_ProgramInfoItem_DocumentDetail>();
            this.jjj_ProgramInfoItem_TextDetail = new HashSet<jjj_ProgramInfoItem_TextDetail>();
            this.jjj_ProgramInfoItem_TimeDetail = new HashSet<jjj_ProgramInfoItem_TimeDetail>();
            this.jjj_ProgramInfoItem_VideoDetail = new HashSet<jjj_ProgramInfoItem_VideoDetail>();
        }
    
        public int ProgramInfoItemID { get; set; }
        public int ProgramInfoID { get; set; }
        public Nullable<int> ProgramInfoItemType { get; set; }
        public string ProgramInfoItemTitle { get; set; }
        public Nullable<decimal> ProgramInfoItemLeft { get; set; }
        public Nullable<decimal> ProgramInfoItemTop { get; set; }
        public Nullable<int> ProgramInfoItemWidth { get; set; }
        public Nullable<int> ProgramInfoItemHeight { get; set; }
        public Nullable<int> ProgramInfoItemLayer { get; set; }
        public Nullable<int> IsShowWater { get; set; }
        public string ProgramInfoItemClientId { get; set; }
        public string Second_ProgramInfoItem_ServerBack { get; set; }
        public Nullable<int> TopMost { get; set; }
    
        public virtual ICollection<jjj_ProgramInfoItem_DocumentDetail> jjj_ProgramInfoItem_DocumentDetail { get; set; }
        public virtual ICollection<jjj_ProgramInfoItem_TextDetail> jjj_ProgramInfoItem_TextDetail { get; set; }
        public virtual ICollection<jjj_ProgramInfoItem_TimeDetail> jjj_ProgramInfoItem_TimeDetail { get; set; }
        public virtual ICollection<jjj_ProgramInfoItem_VideoDetail> jjj_ProgramInfoItem_VideoDetail { get; set; }
        public virtual jjj_ProgramInfoList jjj_ProgramInfoList { get; set; }
    }
}
