//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultimediaSysServer.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class jjj_TerminalEquipmentSerialCommand
    {
        public int TerSerialCommandID { get; set; }
        public string SendAdminName { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
        public Nullable<int> CommandTypeId { get; set; }
        public Nullable<int> TerminalEquipmentID { get; set; }
        public string SendContent { get; set; }
        public Nullable<int> SendStatus { get; set; }
        public Nullable<System.DateTime> ReceiveBackTime { get; set; }
    
        public virtual jjj_TerminalEquipmentList jjj_TerminalEquipmentList { get; set; }
    }
}
