//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultimediaSysServer.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class jjj_MaterialManagementDetail
    {
        public int ID { get; set; }
        public int MaterialID { get; set; }
        public string FileName { get; set; }
        public Nullable<decimal> FileSize { get; set; }
        public Nullable<int> FileType { get; set; }
        public string FilePath { get; set; }
        public string FileSuffixName { get; set; }
        public Nullable<System.DateTime> UploadTime { get; set; }
        public Nullable<int> UploadUserId { get; set; }
        public string TransformFilePath { get; set; }
        public string TransformFileSuffixName { get; set; }
        public string ThumbnailImgPath { get; set; }
        public string OriginalFileName { get; set; }
    
        public virtual jjj_MaterialManagement jjj_MaterialManagement { get; set; }
        public virtual jjj_users jjj_users { get; set; }
    }
}
