//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultimediaSysServer.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class jjj_ProgramInfoItem_TextDetail
    {
        public int ID { get; set; }
        public int ProgramInfoItemID { get; set; }
        public Nullable<int> TextLayer { get; set; }
        public string TextContent { get; set; }
        public Nullable<int> TextDirectionType { get; set; }
        public Nullable<int> IsBackgroundTransparent { get; set; }
        public string BackgroundColor { get; set; }
        public string foreColor { get; set; }
        public Nullable<int> IsBold { get; set; }
        public string FontFamily { get; set; }
        public Nullable<int> FontSize { get; set; }
        public Nullable<int> PlayCount { get; set; }
        public Nullable<int> PlaySpeed { get; set; }
        public string ProgramInfoItemTextClientId { get; set; }
        public string Second_ProgramInfoItemText_ServerBack { get; set; }
    
        public virtual jjj_ProgramInfoListItem jjj_ProgramInfoListItem { get; set; }
    }
}
