//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultimediaSysServer.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class jjj_MaterialManagement
    {
        public jjj_MaterialManagement()
        {
            this.jjj_MaterialManagementDetail = new HashSet<jjj_MaterialManagementDetail>();
        }
    
        public int MaterialID { get; set; }
        public string MaterialFolderName { get; set; }
        public Nullable<int> parentId { get; set; }
        public Nullable<int> layer { get; set; }
        public Nullable<System.DateTime> updateTime { get; set; }
        public Nullable<int> CreateUserId { get; set; }
        public string SouthWing_MaterialID { get; set; }
    
        public virtual jjj_users jjj_users { get; set; }
        public virtual ICollection<jjj_MaterialManagementDetail> jjj_MaterialManagementDetail { get; set; }
    }
}
