//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultimediaSysServer.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class jjj_ProgramInfoItem_DocumentDetail
    {
        public int ID { get; set; }
        public int ProgramInfoItemID { get; set; }
        public Nullable<int> DocumentLayer { get; set; }
        public Nullable<int> TimeLength { get; set; }
        public Nullable<int> CartoonType { get; set; }
        public string DocumentUrl { get; set; }
        public string ProgramInfoItemDocumentClientId { get; set; }
        public string Second_ProgramInfoItemDocument_ServerBack { get; set; }
    
        public virtual jjj_ProgramInfoListItem jjj_ProgramInfoListItem { get; set; }
    }
}
