//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultimediaSysServer.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class jjj_usergroups
    {
        public jjj_usergroups()
        {
            this.jjj_users = new HashSet<jjj_users>();
        }
    
        public int groupid { get; set; }
        public string grouptitle { get; set; }
        public Nullable<int> powerLevel { get; set; }
        public Nullable<int> joinCondition { get; set; }
        public Nullable<int> telephoneNum { get; set; }
        public Nullable<decimal> telFee100 { get; set; }
        public Nullable<decimal> telFee50 { get; set; }
        public Nullable<decimal> telFee30 { get; set; }
        public Nullable<decimal> p10316 { get; set; }
        public Nullable<decimal> p10317 { get; set; }
        public Nullable<decimal> p10319 { get; set; }
        public Nullable<decimal> p10320 { get; set; }
        public Nullable<decimal> p10321 { get; set; }
        public Nullable<decimal> p10322 { get; set; }
        public Nullable<decimal> p10323 { get; set; }
        public Nullable<decimal> p11256 { get; set; }
        public Nullable<decimal> p11257 { get; set; }
        public Nullable<decimal> p11258 { get; set; }
        public Nullable<decimal> p11259 { get; set; }
        public Nullable<decimal> p11260 { get; set; }
        public Nullable<decimal> p11262 { get; set; }
        public Nullable<decimal> p11263 { get; set; }
        public Nullable<decimal> p11608 { get; set; }
        public Nullable<int> parentGroupId { get; set; }
        public Nullable<int> layer { get; set; }
        public string groupDescription { get; set; }
    
        public virtual ICollection<jjj_users> jjj_users { get; set; }
    }
}
