//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultimediaSysServer.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class jjj_BackgroundWeb_OperatePower
    {
        public jjj_BackgroundWeb_OperatePower()
        {
            this.jjj_user_OperatePower = new HashSet<jjj_user_OperatePower>();
        }
    
        public int OperatePowerId { get; set; }
        public string OperatePowerName { get; set; }
        public string OperatePowerURL { get; set; }
        public Nullable<int> ParentOperatePowerId { get; set; }
        public Nullable<int> layer { get; set; }
    
        public virtual ICollection<jjj_user_OperatePower> jjj_user_OperatePower { get; set; }
    }
}
