//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultimediaSysServer.EntityModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MultimediaSYSEntities : DbContext
    {
        public MultimediaSYSEntities()
            : base("name=MultimediaSYSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<area> area { get; set; }
        public virtual DbSet<bankcode> bankcode { get; set; }
        public virtual DbSet<city> city { get; set; }
        public virtual DbSet<jjj_adminsessions> jjj_adminsessions { get; set; }
        public virtual DbSet<jjj_BackgroundWeb_OperatePower> jjj_BackgroundWeb_OperatePower { get; set; }
        public virtual DbSet<jjj_MaterialManagement> jjj_MaterialManagement { get; set; }
        public virtual DbSet<jjj_MaterialManagementDetail> jjj_MaterialManagementDetail { get; set; }
        public virtual DbSet<jjj_TerminalEquipmentCategory> jjj_TerminalEquipmentCategory { get; set; }
        public virtual DbSet<jjj_TerminalEquipmentList> jjj_TerminalEquipmentList { get; set; }
        public virtual DbSet<jjj_user_OperatePower> jjj_user_OperatePower { get; set; }
        public virtual DbSet<jjj_usergroups> jjj_usergroups { get; set; }
        public virtual DbSet<jjj_users> jjj_users { get; set; }
        public virtual DbSet<province> province { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<jjj_TerminalEquipmentSerialCommand> jjj_TerminalEquipmentSerialCommand { get; set; }
        public virtual DbSet<jjj_ProgramInfoItem_DocumentDetail> jjj_ProgramInfoItem_DocumentDetail { get; set; }
        public virtual DbSet<jjj_ProgramInfoItem_ImageDetail> jjj_ProgramInfoItem_ImageDetail { get; set; }
        public virtual DbSet<jjj_ProgramInfoItem_TextDetail> jjj_ProgramInfoItem_TextDetail { get; set; }
        public virtual DbSet<jjj_ProgramInfoItem_TimeDetail> jjj_ProgramInfoItem_TimeDetail { get; set; }
        public virtual DbSet<jjj_ProgramInfoItem_VideoDetail> jjj_ProgramInfoItem_VideoDetail { get; set; }
        public virtual DbSet<jjj_ProgramInfoList> jjj_ProgramInfoList { get; set; }
        public virtual DbSet<jjj_ProgramInfoListItem> jjj_ProgramInfoListItem { get; set; }
        public virtual DbSet<jjj_ProgramSendSerialList> jjj_ProgramSendSerialList { get; set; }
        public virtual DbSet<jjj_user_DrinkCostSerialList> jjj_user_DrinkCostSerialList { get; set; }
        public virtual DbSet<jjj_TerminalSwitchScreenTime> jjj_TerminalSwitchScreenTime { get; set; }
    }
}
